In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
import pydotplus
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
data = load_iris()
x = data.data
y = data.target
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=32)
clf = DecisionTreeClassifier(criterion='entropy')
clf.fit(x_train,y_train)
y_train_pred = clf.predict(x_train)
y_test_pred = clf.predict(x_test)
con_met_train = confusion_matrix(y_train,y_train_pred)
con_met_test = confusion_matrix(y_test,y_test_pred)
print(con_met_train)
print(con_met_test)
dot_data = export_graphviz(clf,out_file=None)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf("iris.pdf")

[[34  0  0]
 [ 0 39  0]
 [ 0  0 39]]
[[16  0  0]
 [ 0 11  0]
 [ 0  0 11]]


True