In [1]:
import numpy as np
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,0,0,1]).reshape(4,1)
x.shape , y.shape , y

((4, 2),
 (4, 1),
 array([[0],
        [0],
        [0],
        [1]]))

In [2]:
def sig(z):
    return 1/(1+np.exp(-z))

In [3]:
weights = 2*np.random.random((2,1))-1
bias = 2*np.random.random(1)-1
weights, bias

(array([[0.3070816],
        [0.6391044]]),
 array([0.72632051]))

In [4]:
# forward propagation 
output_ip_layer = x
output_op_layer = sig(np.dot(output_ip_layer,weights)+bias)
output_op_layer

array([[0.67399731],
       [0.79663997],
       [0.73757493],
       [0.84190972]])

In [5]:
def derivative_sig(z):
    return sig(z)*(1-sig(z))

In [6]:
# code for backpropagation and gradient descent to achieve the correct weights
lr = 0.1
for iter in range(10000):
    output_ip_layer = x
    output_op_layer = sig(np.dot(output_ip_layer,weights)+bias)

    first_term = output_op_layer - y # d(E)/d(oj)
    ip_last_layer = sig(np.dot(output_ip_layer,weights)) + bias 
    second_term = derivative_sig(ip_last_layer) #d(oj)/d(ip_j)
    first_two = first_term*second_term
    changes = np.zeros((2,1),dtype=float) #array for each d(E)/d(w_ij) same shape as weight to change weights
    # Here the third term - d(oj)/d(wij) = oi, which is output_input_layer[i][feature]
    for fea in range(2):
        for j in range(4):
            changes[fea][0] += first_two[j][0] * output_ip_layer[j][fea]
    weights = weights - lr*changes
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0]*1
    bias = bias - lr*bias_change

output_op_layer = sig(np.dot(output_ip_layer,weights)+bias)
weights, bias , output_op_layer


(array([[3.52683744],
        [3.5277767 ]]),
 array([-5.47599925]),
 array([[0.00416859],
        [0.1247473 ],
        [0.12464478],
        [0.82900826]]))